#include <cstdio>
#include <fstream>
#include <iostream>
#include <ostream>
#include <regex>
#include <bitset>

#include "include/curl_easy.h"
#include "include/curl_exception.h"
#include "include/curl_form.h"
#include "include/curl_ios.h"
#include "include/nlohmann/json.hpp"

using std::cout;
using std::endl;
using std::ofstream;
using std::ostringstream;

using curl::curl_easy;
using curl::curl_easy_exception;
using curl::curl_ios;
using json = nlohmann::json;

int main(int argc, char** argv){
    

//     json result;
//     result["name"]="A Little Snitch Rule Group";
//     result["description"]="Little Snitch rule group generated by surge2littlesnitch.";

//     if (argc < 2) {
//     cout << "Usage: surge2ls <source_file_url>" << endl;
//     exit(1);
//   }

//   ostringstream str;
//   curl_ios<ostringstream> writer(str);
//   curl_easy easy(writer);

//   easy.add<CURLOPT_URL>(argv[1]);
//   easy.add<CURLOPT_FOLLOWLOCATION>(1L);
//   try {
//     easy.perform();
//   } catch (curl_easy_exception &exception) {
//     std::cerr << exception.what() << endl;
//     exception.print_traceback();
//   }

//     return 0;
}